site_name: treco
site_url: https://github.com/miodine/treco
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - API: api_reference.md
  - Modules:
    - core: modules/core.md
    - forecasts: modules/core.md
    - indicators: modules/indicators.md
    - markets: modules/markets.md
    - extras: modules/extras.md

theme: readthedocs